### ISSUE TITLE
bug: wrong source code layout by utilizing download_src

### ISSUE THREAD

**Issue by learnerLj** [lmy375/peth#6]
The file layout shows below after successfully getting the source code from https://bscscan.com/address/0x9059f2f644402db18155b7917762823a58962397#code
![image](https://user-images.githubusercontent.com/72367122/209795044-ceb25956-ad79-4d96-b17f-2c3485a6b611.png)

But the contract `0x9059F2F644402DB18155B7917762823A58962397/contracts/math/Math.sol` is not in the proper directory because of the statement `import "@openzeppelin/contracts/math/Math.sol";` at line#7 at  `contracts/v2/MerlinStrategyAlpacaBNB.sol` 
![image](https://user-images.githubusercontent.com/72367122/209796063-42461e8f-ed92-40dd-bda9-fc3cd2bea3e8.png)

**Comment by learnerLj** [comment]
It is the same problem with  `contracts/token/ERC20/IERC20.sol `.

**Comment by lmy375** [comment]
fix in v1.0.3
