### ISSUE TITLE
type object 'Web3' has no attribute 'isAddress'

### ISSUE THREAD

**Issue by 5z1punch** [lmy375/peth#9]
Great project!

when calling download_source 0xxxx, raise an error "type object 'Web3' has no attribute 'isAddress'"

thanks!

**Comment by lmy375** [comment]
Good catch! 
Rollback your web3.py to 5.31.1 and it should work. 
https://github.com/lmy375/peth/commit/bdaf8737608b4ad4ae6c4c754d20e94bb249c574
